# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b71ed6e62e7ba71097c02d6bc6f29deb5f605474b3a27a980c2f9bea810903f1fdc7c6a16d5d682549445bb72a9a89dcc2ea349d867ca24e56fb0d60ab8c170

test:
  secret_key_base: 900f1a4d8436f5be0f8e8a786fd47ca78843ac311f0019b2a78fb92f90e3ac1a15a5ea5a8d6e8bad54d9d8eb9310da72719ba656bd17d991a1d2164cec7b722e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
